@echo off
rem
rem $Id: BuildLib.bat,v 1.2 2013-07-01 02:03:35 fyurisich Exp $
rem
rem Build ooHG libraries from official distro
rem
rem Use: BuildLib [f] [hbmk2 options]
rem f parameter redirectes all output to a file named error.log
rem
rem hbmk2 usefull options:
rem -rebuild to force compiling of all sources
rem -trace to see the commands generated by hbmk2

cls

set ooHG_INSTALL=c:\oohg
set MINGW=%ooHG_INSTALL%\mingw
set HRB_DIR=%ooHG_INSTALL%\harbour

set TPATH=%PATH%
set PATH=%HRB_DIR%\bin;%MINGW%\bin

if exist error.log del error.log

if .%1.==.f. goto FILE
if .%1.==.F. goto FILE

:SCREEN
hbmk2 oohg.hbp      %1 %2 %3 %4 %5 %6 %7 %8 %9
hbmk2 miniprint.hbp %1 %2 %3 %4 %5 %6 %7 %8 %9
hbmk2 hbprinter.hbp %1 %2 %3 %4 %5 %6 %7 %8 %9
goto FIN

:FILE
hbmk2 oohg.hbp      %2 %3 %4 %5 %6 %7 %8 %9 >> error.log 2>&1
hbmk2 miniprint.hbp %2 %3 %4 %5 %6 %7 %8 %9 >> error.log 2>&1
hbmk2 hbprinter.hbp %2 %3 %4 %5 %6 %7 %8 %9 >> error.log 2>&1
goto FIN

:FIN
set PATH=%TPATH%

rem EOF
