
name: OOHG Harbour 3.4 mingw 7.3 32/64 bits

on:
  push:
  schedule:
   - cron: "0 5 1 * *"
  workflow_dispatch:
    inputs:
      name:
        description: 'Harbour 3.4 mingw 7.3'
        default: 'oohg_hb34_0703'
        required: true

jobs:

  Build:
    runs-on: windows-latest
    steps:

    - name: Harbour
      uses: JoseQuintas/action-download-artifact@v2
      with:
         workflow: hb34_0703.yml
         workflow_conclusion: success
         name: hb34_0703
         path: c:\temp
         repo: JoseQuintas/harbour_34

    - name: mingw
      uses: JoseQuintas/action-download-artifact@v2
      with:
         workflow: hb34_0703.yml
         workflow_conclusion: success
         name: mingw_0703
         path: c:\temp
         repo: JoseQuintas/harbour_34

    - name: Unzip
      run: |
         c:
         md c:\temp\harbour
         7z x -y c:\temp\hb34_0703.7z -oc:\temp\harbour
         7z x -y c:\temp\mingw_0703.7z -oc:\temp\mingw

    - name: oohg
      env:
         REPO: ${{ github.repository }}
      run: |
         c:
         md \temp\harbour\addons
         git clone https://github.com/$env:repo c:\temp\harbour\addons\oohg\ --depth 1

    - name: Build 32 bits
      env:
         HB_COMPILER: mingw
         HB_INSTALL_PREFIX: c:\temp\harbour
         PATH: c:\temp\harbour\bin;c:\temp\mingw\mingw64\bin
      run: |
         c:
         cd c:\temp\harbour\addons\oohg
         hbmk2 oohg.hbp -workdir=c:\temp

    - name: Build 64 bits
      env:
         HB_COMPILER: mingw64
         HB_INSTALL_PREFIX: c:\temp\harbour
         PATH: c:\temp\harbour\bin;c:\temp\mingw\mingw64\bin
      run: |
         c:
         cd \temp\harbour\addons\oohg
         hbmk2 oohg.hbp -workdir=c:\temp

    - name: Zip
      env:
         PATH: c:\program files\7-zip
      run: |
         c:
         cd \temp\harbour
         7z a -r c:\temp\oohg_hb34_0703.7z c:\temp\harbour\addons\oohg\*.*  -xr'!.git' -xr'!.github' -xr'!.hbmk'

    - name: Save hb/oohg
      uses: actions/upload-artifact@v2
      with:
         name: oohg_hb34_0703
         path: c:\temp\oohg_hb34_0703.7z

#    - name: Save mingw
#      uses: actions/upload-artifact@v2
#      with:
#         name: mingw_0703
#         path: c:\temp\mingw_0703.7z
